export const GAP_STEPS = [0, 4, 8, 12, 16, 24] as const
export const PADDING_STEPS = [0, 8, 16, 24, 32] as const
export const RADIUS_STEPS = [0, 8, 16, 24] as const
export const RESULT_STORAGE_KEY = 'bluebooth:last'
export const RESULT_DATABASE_NAME = 'bluebooth-local'
export const RESULT_DATABASE_VERSION = 1
export const RESULT_STORE_NAME = 'results'
export const LAST_RESULT_ID = 'last'
export const CUSTOM_FRAME_ACCEPT = ['image/png', 'image/webp'] as const
export const CUSTOM_FRAME_MAX_BYTES = 10 * 1024 * 1024
export const CUSTOM_FRAME_MAX_DIMENSION = 6000
export const TEMP_CAPTURE_MAX_DIMENSION = 1920
